#!/usr/bin/env node
/**
 * Copies docs/TERMS.md and docs/PRIVACY_POLICY.md into the app (src/legal/generated.ts),
 * so the app always shows exactly what's in the docs.
 *
 * Run after editing either document:   npm run sync-legal
 * (A unit test fails if you forget, so the two can never drift apart.)
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

function load(file) {
  const raw = fs.readFileSync(path.join(root, 'docs', file), 'utf8');
  // Drop reviewer notes (<!-- ... -->); the app shows only the policy itself.
  const text = raw.replace(/<!--[\s\S]*?-->\s*/g, '').trim() + '\n';
  const match = /^\*\*Version:\*\*\s*(\d{4}-\d{2}-\d{2})\s*$/m.exec(text);
  if (!match) throw new Error(`docs/${file} needs a line like: **Version:** 2026-09-27`);
  return { text, version: match[1] };
}

const terms = load('TERMS.md');
const privacy = load('PRIVACY_POLICY.md');

const out = `// GENERATED by scripts/sync-legal.js from docs/TERMS.md and docs/PRIVACY_POLICY.md.
// Do not edit by hand. Edit the docs, then run: npm run sync-legal

export const TERMS_VERSION = ${JSON.stringify(terms.version)};
export const TERMS_MD = ${JSON.stringify(terms.text)};

export const PRIVACY_VERSION = ${JSON.stringify(privacy.version)};
export const PRIVACY_MD = ${JSON.stringify(privacy.text)};
`;

fs.writeFileSync(path.join(root, 'src', 'legal', 'generated.ts'), out);
console.log(`Synced Terms (${terms.version}) and Privacy Policy (${privacy.version}) into the app.`);
